version: '3.9'
services:
  castelferro:
    image: castelferro:v2
    container_name: castelferro-dev

    ports:
      - "3000:3000"

    networks:
      - pg-network

 
networks:
  pg-network:
    driver: bridge